### ISSUE TITLE
NPM@0.2.0 Broken

### ISSUE THREAD

**Issue by Keidrych** [leoafarias/neardb#20]
Heya, really excited about this project and its goals, unfortunately the latest relase: 0.2.0 on NPM is broken, the s3_1.default is present, which has been addressed in future versions & your current codebase.

The beta release is working fine. 

Please update the NPM release version when convenient

Additionally if you added the following script, it would enable people to checkout from github directly autocompiling ts to js for your matching releases
`"postinstall": "tsc --outDir ./build"`

https://stackoverflow.com/a/58257602

**Comment by leoafarias** [comment]
@Keidrych I just pushed an update 0.2.1. I will be moving the npm publish to the CI side, to avoid this from happening in the future.
