### ISSUE TITLE
How to get a list of PathItem?

### ISSUE THREAD

**Issue by murka** [leoafarias/neardb#32]
For example, I created `country/russia` and `country/usa` by `collection`:

```ts
  const GDPofRussia = await neardb.collection('country/russia').doc('GDP').set({
    value: '1699876580000',
    currency: 'USD'
  })

  const GDPofUSA = await neardb.collection('country/usa').doc('GDP').set({
    value: '21433226580000',
    currency: 'USD'
  })
```

and I want to get a list of `country` collection:  
```javascript
['russia', 'usa']
```
>  Maybe, your implementation are different

**Comment by leoafarias** [comment]
This is currently not possible. I am in the middle of architecture a version that would allow for this type of behavior but it might take a while to make these changes. A solution would be to add countries in the same docs as object keys.
