### ISSUE TITLE
Add Google Cloud Storage example

### ISSUE THREAD

**Issue by dandv** [leoafarias/neardb#7]
How would one use GCS? I can't quite figure it out from the README.

By comparison, @lukechilds's [keyv](https://github.com/lukechilds/keyv) is much clearer in how to get started.

**Comment by leoafarias** [comment]
I have added the steps needed to get started using Google Cloud Storage with NearDB https://www.notion.so/Google-Cloud-Storage-02b21bb5b9e643c39f6845b873f19ef4
